version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:erbium

jobs:
  deploy-npm:
    executor: node
    working_directory: ~/project
    steps:
      - run:
          name: Populate .npmrc
          command: |
            echo "@cazoo-uk:registry=https://npm.pkg.github.com/" >> .npmrc
            echo "//npm.pkg.github.com/:_authToken=${CAZOO_GITHUB_NPM_TOKEN}" >> .npmrc
      - run: npm ci
      - run:
          name: Deploy NPM package
          command: |
            npm publish

workflows:
  version: 2
  release-eslint-npm:
    jobs:
      - deploy-npm:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)/
          context: cazoo-npm
