on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: npm ci
            - name: Make stable release to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.CAZOO_NPM_TOKEN}}
